---
_label: "Resources"
_icon: icon.folder
---

[[directory-index]]

This section documents the knowledge learnt from various sources during the implementation of `dboxide`:

- [**`rust-analyzer`**](01-rust-analyzer/index): An implementation of LSP for the Rust programming language - a good reference model.
- [**`rustc Development Guide`**](02-rustc/index): Covers incremental compilation persistence, cache management, and stable hashing.
- [**`libsyntax`**](03-libsyntax): Rust compiler's crate that documents some design notes on tree structure and parser.
- [**`salsa`**](04-salsa/index): An incremental computation framework for building responsive compilers and language servers.
- [**DSL**](05-dsl/index): General DSL design philosophy, covering both the structural DSL and logic DSL aspects of dboxide.
