---
_type: Concept
_label: "Syntax-Directed Translation"
status: 'learning'
tags:
  - 'external dsl'
  - 'parsing'
depends_on:
  - fref("02-research/04-glossary/grammar.td")
  - fref("02-research/04-glossary/bnf.td")
---

A parsing approach that defines a formal grammar and uses it to drive the parse. Handles hierarchic structure naturally. The grammar can be turned into a parser via a Recursive Descent Parser, Parser Combinator, or Parser Generator.
