---
_label: "Research"
_icon: icon.library
---

[[directory-index]]

This section documents the research done for the `dboxide` project. It is divided into two main parts:

*   [**Research Plan**](01-research-plan): This page outlines the research plan, including the list of topics to be investigated.
*   [**Resources**](02-resources/index): This page documents the knowledge learnt from various resources.
*   [**Glossary**](04-glossary): This page contains brief explanations of the concepts and techniques researched for the project.
